version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "{{appName}}"
s3_bucket = "aws-sam.functions"
s3_prefix = "cloudFormationStack-{{appName}}"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
